INSERT INTO TB_CATEGORY (DATE_INCLUSION, DATE_UPDATE, DESCRIPTION, MONTHLY_BUDGET, NAME, TOTAL_SPEND) VALUES (NOW(), NULL, 'Category desined fooding.', 700.00, 'Fodding', 0);
INSERT INTO TB_CATEGORY (DATE_INCLUSION, DATE_UPDATE, DESCRIPTION, MONTHLY_BUDGET, NAME, TOTAL_SPEND) VALUES (NOW(), NULL, 'Category desined fooding.', 700.00, 'Fodding', 0);
INSERT INTO TB_CATEGORY (DATE_INCLUSION, DATE_UPDATE, DESCRIPTION, MONTHLY_BUDGET, NAME, TOTAL_SPEND) VALUES (NOW(), NULL, 'Category desined fooding.', 700.00, 'Fodding', 0);

INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 2900.00, 'Adding salary amount.', 1, 1, 4);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 2900.00, 'Adding salary amount.', 1, 0, 3);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 1550.00, 'Adding salary amount.', 1, 0, 3);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 900.00, 'Adding salary amount.', 1, 1, 4);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 200.00, 'Adding salary amount.', 1, 0, 2);

INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 2900.00, 'Adding salary amount.', 2, 0, 3);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 2900.00, 'Adding salary amount.', 2, 1, 1);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 1550.00, 'Adding salary amount.', 2, 1, 2);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 900.00, 'Adding salary amount.', 2, 0, 2);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 200.00, 'Adding salary amount.', 2, 0, 1);

INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 2900.00, 'Adding salary amount.', 3, 1, 3);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 2900.00, 'Adding salary amount.', 3, 1, 2);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 1550.00, 'Adding salary amount.', 3, 0, 2);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 900.00, 'Adding salary amount.', 3, 0, 1);
INSERT INTO TB_BALANCE (DATE_INCLUSION, DATE_UPDATE, ADDITION_DATE, BALANCE_VALUE, DESCRIPTION, ID_CATEGORY, TYPE_BALANCE, TYPE_PAYMENT) VALUES (NOW(), NULL, TIMESTAMP WITH TIME ZONE '2023-03-27', 200.00, 'Adding salary amount.', 3, 0, 2);

INSERT INTO TB_DEBT (NAME, DEBT_AMOUNT, MONTH_INTEREST, DATE_DUE) VALUES ('Pagamento conta de água', 164.0, 1.0, '2023-03-27');
INSERT INTO TB_DEBT (NAME, DEBT_AMOUNT, MONTH_INTEREST, DATE_DUE) VALUES ('Pagamento conta de luz', 300.0, 1.0, '2023-03-28');
INSERT INTO TB_DEBT (NAME, DEBT_AMOUNT, MONTH_INTEREST, DATE_DUE) VALUES ('Pagamento conta de gaz', 75.0, 1.0, '2023-03-30');
